server:
  port: 9098
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-exception: false
    include-stacktrace: never
    path: '/error'
    whitelabel:
      enabled: true

server.error:

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/memoProject?autoReconnect=true&serverTimezone=Asia/Seoul
    username: 'sunshine'
    password: '!Korea8080'

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  jackson:
    serialization:
      fail-on-empty-beans: false

mybatis:
  type-aliases-package: com.ppuni.memo.DAO.HomeDAO
